CREATE TABLE `rental_order_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`equipmentItemId` int NOT NULL,
	`equipmentName` varchar(255) NOT NULL,
	`equipmentBrand` varchar(128),
	`rentalDays` int NOT NULL,
	`dailyRate` decimal(10,2) NOT NULL,
	`lineTotal` decimal(12,2) NOT NULL,
	`discountedTotal` decimal(12,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rental_order_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rental_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`membershipId` int,
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(64) NOT NULL,
	`companyName` varchar(255),
	`membershipPlan` enum('payg','trade_pro') NOT NULL DEFAULT 'payg',
	`rentalStartDate` timestamp NOT NULL,
	`rentalEndDate` timestamp NOT NULL,
	`rentalDays` int NOT NULL,
	`subtotal` decimal(12,2) NOT NULL,
	`discountPercent` decimal(5,2) NOT NULL DEFAULT '0',
	`discountAmount` decimal(12,2) NOT NULL DEFAULT '0',
	`deliveryFee` decimal(10,2) NOT NULL DEFAULT '0',
	`depositAmount` decimal(12,2) NOT NULL DEFAULT '0',
	`depositWaived` boolean NOT NULL DEFAULT false,
	`totalAmount` decimal(12,2) NOT NULL,
	`deliveryType` enum('delivery','self_collection') NOT NULL DEFAULT 'self_collection',
	`deliveryAddress` text,
	`returnAddress` text,
	`status` enum('pending_payment','paid','confirmed','active','completed','cancelled','refunded') NOT NULL DEFAULT 'pending_payment',
	`stripePaymentIntentId` varchar(128),
	`stripeCheckoutSessionId` varchar(128),
	`stripeInvoiceId` varchar(128),
	`paidAt` timestamp,
	`adminNotifiedAt` timestamp,
	`customerEmailSentAt` timestamp,
	`customerNotes` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rental_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_memberships` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`plan` enum('payg','trade_pro') NOT NULL DEFAULT 'payg',
	`status` enum('pending','active','suspended','cancelled') NOT NULL DEFAULT 'pending',
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(64) NOT NULL,
	`companyName` varchar(255),
	`businessRegNo` varchar(128),
	`monthlyBudget` varchar(64),
	`hkidNumber` varchar(32),
	`hkidPhotoUrl` text,
	`hkidPhotoKey` varchar(512),
	`hkidVerified` boolean NOT NULL DEFAULT false,
	`hkidVerifiedAt` timestamp,
	`stripeCustomerId` varchar(128),
	`stripeSubscriptionId` varchar(128),
	`membershipFee` decimal(10,2),
	`nextBillingDate` timestamp,
	`returnAddress` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_memberships_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_memberships_userId_unique` UNIQUE(`userId`)
);
